# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
#impoting Numpy
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [5]:
print(np.__version__)


2.3.2


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [11]:
###Code to Generate 2x3x5 3-dimensional
a = np.random.rand(2,3,5)



### 4. Print a.


In [9]:
print(a)


[[[0.60005012 0.62979037 0.29584423 0.26706694 0.36569137]
  [0.7019913  0.45321421 0.87592727 0.99124171 0.79958779]
  [0.77123093 0.6038526  0.47463154 0.6116087  0.88917302]]

 [[0.47336605 0.3060203  0.27300868 0.39342892 0.08825467]
  [0.90797375 0.86885965 0.79505574 0.56182357 0.8171599 ]
  [0.08121221 0.01280539 0.1585083  0.19861198 0.74433936]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [15]:
b = np.ones((5,2,3))



### 6. Print b.


In [17]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [21]:
a_size = a.shape
b_size = b.shape

print("The shape of a is ", a_size)
print("The shape of b is ", b_size)


The shape of a is  (2, 3, 5)
The shape of b is  (5, 2, 3)



### 8. Are you able to add a and b? Why or why not?


In [23]:
sum_a_b = a + b
print(sum_a_b)


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

No, we cannot add a and b directly, because their shapes are not compatible for broadcasting.



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [32]:
c = np.transpose(b, (1, 2, 0))

print("Shape of b:", b.shape)
print("Shape of c:", c.shape)

Shape of b: (5, 2, 3)
Shape of c: (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [34]:
d = a + c
print(d)


[[[1.91256705 1.1622267  1.34831705 1.53203551 1.72012622]
  [1.70557118 1.92718155 1.77942373 1.38396093 1.07512003]
  [1.98745358 1.08040072 1.8860378  1.25416817 1.8871238 ]]

 [[1.06313878 1.97843019 1.75260685 1.71855922 1.92060556]
  [1.13339974 1.61741081 1.77347166 1.09963953 1.53385002]
  [1.37195985 1.54519264 1.96143851 1.08445795 1.3116867 ]]]


We can safely add a + c because their shapes match

Every element in d is exactly 1 unit larger than the corresponding element in a
### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [37]:
print("a :", a)
print("d :", d)


a : [[[0.91256705 0.1622267  0.34831705 0.53203551 0.72012622]
  [0.70557118 0.92718155 0.77942373 0.38396093 0.07512003]
  [0.98745358 0.08040072 0.8860378  0.25416817 0.8871238 ]]

 [[0.06313878 0.97843019 0.75260685 0.71855922 0.92060556]
  [0.13339974 0.61741081 0.77347166 0.09963953 0.53385002]
  [0.37195985 0.54519264 0.96143851 0.08445795 0.3116867 ]]]
d : [[[1.91256705 1.1622267  1.34831705 1.53203551 1.72012622]
  [1.70557118 1.92718155 1.77942373 1.38396093 1.07512003]
  [1.98745358 1.08040072 1.8860378  1.25416817 1.8871238 ]]

 [[1.06313878 1.97843019 1.75260685 1.71855922 1.92060556]
  [1.13339974 1.61741081 1.77347166 1.09963953 1.53385002]
  [1.37195985 1.54519264 1.96143851 1.08445795 1.3116867 ]]]


Every element in d is exactly 1 unit greater than the corresponding element in a because the operation performed is element-wise addition. The array c acts as a scalar with the value 1, and in NumPy, adding a scalar to an array triggers broadcasting, a mechanism that automatically applies the scalar addition to each element of the array individually.


### 12. Multiply a and c. Assign the result to e.


In [42]:
e = a * c

print("a :", a)
print("e :", e)

a : [[[0.91256705 0.1622267  0.34831705 0.53203551 0.72012622]
  [0.70557118 0.92718155 0.77942373 0.38396093 0.07512003]
  [0.98745358 0.08040072 0.8860378  0.25416817 0.8871238 ]]

 [[0.06313878 0.97843019 0.75260685 0.71855922 0.92060556]
  [0.13339974 0.61741081 0.77347166 0.09963953 0.53385002]
  [0.37195985 0.54519264 0.96143851 0.08445795 0.3116867 ]]]
e : [[[0.91256705 0.1622267  0.34831705 0.53203551 0.72012622]
  [0.70557118 0.92718155 0.77942373 0.38396093 0.07512003]
  [0.98745358 0.08040072 0.8860378  0.25416817 0.8871238 ]]

 [[0.06313878 0.97843019 0.75260685 0.71855922 0.92060556]
  [0.13339974 0.61741081 0.77347166 0.09963953 0.53385002]
  [0.37195985 0.54519264 0.96143851 0.08445795 0.3116867 ]]]




### 13. Does e equal to a? Why or why not?


a and e are equal because they contain identical data in the same structure, there’s no difference in shape, values, or order



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [45]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print("The maximum value of d is ", d_max)
print("The minimum value of d is ", d_min)
print("The mean value of d is ", d_mean)


The maximum value of d is  1.987453575871026
The minimum value of d is  1.0631387845562688
The mean value of d is  1.5502520680751128



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [61]:
f = np.empty(d.shape)
print(f)

[[[1.91256705 1.1622267  1.34831705 1.53203551 1.72012622]
  [1.70557118 1.92718155 1.77942373 1.38396093 1.07512003]
  [1.98745358 1.08040072 1.8860378  1.25416817 1.8871238 ]]

 [[1.06313878 1.97843019 1.75260685 1.71855922 1.92060556]
  [1.13339974 1.61741081 1.77347166 1.09963953 1.53385002]
  [1.37195985 1.54519264 1.96143851 1.08445795 1.3116867 ]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [65]:
for i in range(2):
    for j in range(3):
        for k in range(5):
            val = d[i, j, k]
            if val == d_min:
                f[i, j, k] = 0
            elif val == d_max:
                f[i, j, k] = 100
            elif val == d_mean:
                f[i, j, k] = 50
            elif d_min < val < d_mean:
                f[i, j, k] = 25
            elif d_mean < val < d_max:
                f[i, j, k] = 75


In [57]:
print(d.shape)

(2, 3, 5)






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [67]:

print("d =")
print(d)
print("\nf =")
print(f)


d =
[[[1.91256705 1.1622267  1.34831705 1.53203551 1.72012622]
  [1.70557118 1.92718155 1.77942373 1.38396093 1.07512003]
  [1.98745358 1.08040072 1.8860378  1.25416817 1.8871238 ]]

 [[1.06313878 1.97843019 1.75260685 1.71855922 1.92060556]
  [1.13339974 1.61741081 1.77347166 1.09963953 1.53385002]
  [1.37195985 1.54519264 1.96143851 1.08445795 1.3116867 ]]]

f =
[[[ 75.  25.  25.  25.  75.]
  [ 75.  75.  75.  25.  25.]
  [100.  25.  75.  25.  75.]]

 [[  0.  75.  75.  75.  75.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  25.  75.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [71]:
f = [[[None for _ in range(len(d[0][0]))] for _ in range(len(d[0]))] for _ in range(len(d))]

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            val = d[i][j][k]
            if val == d_min:
                f[i][j][k] = "A"
            elif val == d_max:
                f[i][j][k] = "E"
            elif val == d_mean:
                f[i][j][k] = "C"
            elif d_min < val < d_mean:
                f[i][j][k] = "B"
            elif d_mean < val < d_max:
                f[i][j][k] = "D"

# Step 4: Print the labeled array
for layer in f:
    print(layer)

[['D', 'B', 'B', 'B', 'D'], ['D', 'D', 'D', 'B', 'B'], ['E', 'B', 'D', 'B', 'D']]
[['A', 'D', 'D', 'D', 'D'], ['B', 'D', 'D', 'B', 'B'], ['B', 'B', 'D', 'B', 'B']]
